---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: delegated
lint:
  name: yamllint
  options:
    config-file: .yamllint
platforms:
  - name: test-epc-centos7-elasticsearch6
    image: CentOS7_64-bit
    shape: large
    region: EPAM-BY2
    wait_timeout: 1800
    groups:
      - ansible_role_elasticsearch_v6_centos
  - name: test-epc-ubuntu1804-elasticsearch6
    image: Ubuntu18.04_64-bit
    shape: large
    region: EPAM-BY2
    wait_timeout: 1800
    groups:
      - ansible_role_elasticsearch_v6_ubuntu
provisioner:
  name: ansible
  playbooks:
    create: ../resources/provisioning/create.yml
    prepare: ../resources/provisioning/prepare.yml
    destroy: ../resources/provisioning/destroy.yml
  config_options:
    ssh_connection:
      control_path: "/var/ans/%%h"
  lint:
    name: ansible-lint
  env:
    ANSIBLE_LIBRARY:
      /home/gitlab-runner/.local/lib/python2.7/site-packages/epam_ansible
scenario:
  name: epc-elasticsearch6
verifier:
  name: testinfra
  options:
    verbose: True
  directory: ../resources/tests/
  lint:
    name: flake8
