---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: ec2
lint: ansible-lint
platforms:
  - name: test-aws-centos7-elasticsearch-7
    image: ami-9887c6e7
    platform: centos7
    instance_type: t3.medium
    region: us-east-1
    vpc_subnet_id: subnet-05a2ef2b767afec50
    assign_public_ip: false
    spot_price: 0.04
    security_group_name:
      - default
    wait_timeout: 1800
    ssh_user: centos
    groups:
      - rhel_family

  - name: test-aws-centos6-elasticsearch-7
    image: ami-1585c46a
    platform: centos6
    instance_type: m4.large
    region: us-east-1
    vpc_subnet_id: subnet-05a2ef2b767afec50
    assign_public_ip: false
    spot_price: 0.04
    security_group_name:
      - default
    wait_timeout: 1800
    ssh_user: centos
    groups:
      - rhel_family
      - yml_config

  - name: test-aws-ubuntu18-elasticsearch-7
    image: ami-012fd5eb46f56731f
    platform: ubuntu18
    instance_type: t3.medium
    region: us-east-1
    vpc_subnet_id: subnet-05a2ef2b767afec50
    assign_public_ip: false
    security_group_name:
      - default
    spot_price: 0.04
    wait_timeout: 1800
    ssh_user: ubuntu
    groups:
      - debian_family

  - name: test-aws-Debian9-elasticsearch-7
    image: ami-003f19e0e687de1cd
    platform: debian9
    instance_type: t3.medium
    region: us-east-1
    vpc_subnet_id: subnet-05a2ef2b767afec50
    assign_public_ip: false
    spot_price: 0.04
    security_group_name:
      - default
    wait_timeout: 1800
    ssh_user: admin
    groups:
      - debian_family

provisioner:
  name: ansible
  log: false
  config_options:
    defaults:
      callback_whitelist: profile_tasks,timer
    ssh_connection:
      pipelining: true
  inventory:
    group_vars:
      yml_config:
        es_config:
          node.name: '{{ ansible_host }}'
          http.port: 9200
          bootstrap.system_call_filter: false
  playbooks:
    create: ../resources/provisioning/AWS/create.yml
    prepare: ../resources/prepare.yml
    destroy: ../resources/provisioning/AWS/destroy.yml
    verify: ../resources/tests/verify.yml
scenario:
  name: cloud-aws-direct-7
verifier:
  name: ansible
