---
- name: "Set elasticsearch version if defined"
  set_fact:
    es_package_name: 'elasticsearch-{{ es_version }}'
  when: .x not in es_version

- name: "Installing Elasticsearch package"
  package:
    name: '{{ es_package_name }}'
    state: present
  register: installed_package
  until: installed_package is succeeded
  become: True
  notify: Restart elasticsearch

- name: "Correcting elasticsearch default settings"
  include_tasks: es-settings.yml
  when: elasticsearch_set_settings

- name: "Installing elasticsearch scripts"
  include_tasks: add-scripts.yml
  when: elasticsearch_scripts_install

- name: "Start elasticsearch"
  service:
    name: elasticsearch
    state: started
    enabled: True
  become: True
  when:
    - es_start_service
