---
- name: Prepare Python
  import_playbook: provisioning/AWS/prepare.yml

- name: Prepare Java
  hosts: all
  strategy: mitogen_linear
  roles:
    - role: lean_delivery.java
      java_major_version: 8
      transport: repositories

- name: Prepare limits
  hosts: rhel_family
  tasks:
    - name: Set Limits
      lineinfile:
        path: /etc/security/limits.d/90-nproc.conf
        line: elasticsearch soft nproc 65535
      become: true
