---
- name: Prepare Python
  import_playbook: provisioning/AWS/prepare.yml

- name: Prepare Java
  hosts: all
  strategy: mitogen_linear
  roles:
    - role: lean_delivery.java
      java_major_version: 8
      transport: repositories
