---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: delegated
lint:
  name: yamllint
  options:
    config-file: .yamllint
platforms:
  - name: test-epc-centos7-elastic
    image: CentOS7_64-bit
    shape: medium
    region: EPAM-BY2
    wait_timeout: 3600
    groups:
      - rhel_family
  - name: test-epc-centos6-elastic
    image: CentOS6_64-bit
    shape: medium
    region: EPAM-BY2
    wait_timeout: 3600
    groups:
      - rhel_family
      - yml_config
  - name: test-epc-ubuntu1804-elastic
    image: Ubuntu18.04_64-bit
    shape: medium
    region: EPAM-BY2
    wait_timeout: 3600
    groups:
      - debian_family
provisioner:
  name: ansible
  log: true
  playbooks:
    create: ../resources/provisioning/EPC/create.yml
    prepare: ../resources/prepare.yml
    destroy: ../resources/provisioning/EPC/destroy.yml
  config_options:
    defaults:
      callback_whitelist: profile_tasks,timer
      strategy_plugins: /tmp/molecule/plugins/mitogen/ansible_mitogen/plugins/strategy
    ssh_connection:
      control_path: "/var/ans/%%h"
  inventory:
    group_vars:
      yml_config:
        es_config:
          node.name: '{{ ansible_host }}'
          http.port: 9200
          bootstrap.system_call_filter: false
  lint:
    name: ansible-lint
  env:
    ANSIBLE_LIBRARY: ${ANSIBLE_LIBRARY}
scenario:
  name: cloud-epc-delegated
verifier:
  name: testinfra
  options:
    verbose: true
  directory: ../resources/tests/
  lint:
    name: flake8
