---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: docker
lint:
  name: yamllint
  options:
    config-file: .yamllint
platforms:
  - name: test-docker-centos7-elasticsearch6
    image: leandelivery/docker-systemd:centos7
    privileged: True
    env:
      TERM: xterm
    groups:
      - rhel_family
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: docker-centos7
verifier:
  name: testinfra
  options:
    verbose: True
  directory: ../resources/tests/
  lint:
    name: flake8
